:output:
    Game:
        :options:
            :fields:
                - id
                - week_id
                - game_started
                - game_finished
                - spread
                - away
                - away_pts
                - home
                - home_pts
                - time_remaining
