:output:
    Game:
        :options:
            :fields:
                - id
                - week_id
                - game_started
                - game_finished
                - spread
                - away
                - away_pts
                - home
                - home_pts
                - time_remaining
                - winner
                - updated_at
    User:
        :options:
            :fields:
                - id
                - email
                - sign_in_count
                - last_sign_in_at
                - last_sign_in_ip
                - updated_at
                - username
                - admin
